### ISSUE TITLE
Result on MOT Chanllenge

### ISSUE THREAD

**Issue by lpplbiubiubiub** [lyp-deeplearning/deep-sort#1]
I think the result you submit that it comes from private detector...

**Comment by lyp-deeplearning** [comment]
sorry,i just submit the results for the first time

**Comment by lyp-deeplearning** [comment]
@lpplbiubiubiub Do you know how to retract the result?

**Comment by lpplbiubiubiub** [comment]
When you submit your result, select public detector or don't public your result...
